js_lines = [
    '// =========================================================================',
    '// OmmNoMi: Configure Survey_Tables Multilingual Options & Dynamic DisplayNames',
    '// Pure ASCII, Redux Protocol, Zero Truncation',
    '// =========================================================================',
    '(function configureSurveyTablesMultilingual() {',
    '    try {',
    '        var store = window.appStore;',
    '        if (!store) { console.error("[ERROR] Redux store not found."); return; }',
    '',
    '        var state = store.getState();',
    '        var h = (state.appTemplate && state.appTemplate.history && state.appTemplate.history[0] && state.appTemplate.history[0].appTemplate) || (state.appTemplate && state.appTemplate.current);',
    '        var schemas = (h && h.AppData && h.AppData.DataSchemas) || [];',
    '        var tIdx = schemas.findIndex(function(s) { return s && s.Name && s.Name.indexOf("Survey_Tables_Schema") >= 0; });',
    '',
    '        if (tIdx === -1) { console.error("[ERROR] Survey_Tables_Schema not found."); return; }',
    '',
    '        var dict = {};',
    '        var tAttrs = schemas[tIdx].Attributes;',
    '',
    '        // 1. Configure Row_Item as Enum of BaseType Ref to AppVariables with contextual Valid_If',
    '        var riIdx = tAttrs.findIndex(function(a) { return a.Name === "Row_Item"; });',
    '        if (riIdx >= 0) {',
    '            var ri = tAttrs[riIdx];',
    '            var rowItemValidIf = \'=IFS([Table_Type] = "Q6_Labor", SELECT(AppVariables[ID], [Column] = "Row_Item_Labor"), [Table_Type] = "Q15_Turnover", SELECT(AppVariables[ID], [Column] = "Row_Item_Turnover"), IN([Table_Type], LIST("Q19_Capital", "Q20_Loan_Usage")), SELECT(AppVariables[ID], [Column] = "Row_Item_Capital"), [Table_Type] = "Q22_Trajectory", SELECT(AppVariables[ID], [Column] = "Row_Item_Trajectory"), TRUE, SELECT(AppVariables[ID], [Table] = "Survey_Tables"))\';',
    '            ri.Type = "Enum";',
    '            ri.BaseType = "Ref";',
    '            ri.ReferencedTableName = "AppVariables";',
    '            ri.ReferencedRootTableName = "AppVariables";',
    '            ri.Valid_If = rowItemValidIf;',
    '            ri.ValidIf = rowItemValidIf;',
    '            ri.EnumValues = [];',
    '            ri.Description = "";',
    '            ri.DisplayName = \'=LOOKUP("Q_ST_ROW_ITEM", "AppVariables", "ID", "Label")\';',
    '',
    '            var riAux = {};',
    '            try { riAux = typeof ri.TypeAuxData === "string" ? JSON.parse(ri.TypeAuxData) : (ri.TypeAuxData || {}); } catch(e) {}',
    '            riAux.BaseType = "Ref";',
    '            riAux.ReferencedTableName = "AppVariables";',
    '            riAux.ReferencedRootTableName = "AppVariables";',
    '            riAux.ReferencedKeyColumn = "ID";',
    '            riAux.Valid_If = rowItemValidIf;',
    '            ri.TypeAuxData = riAux;',
    '',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].Type"] = "Enum";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].BaseType"] = "Ref";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].ReferencedTableName"] = "AppVariables";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].ReferencedRootTableName"] = "AppVariables";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].Valid_If"] = rowItemValidIf;',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].Description"] = "";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].DisplayName"] = \'=LOOKUP("Q_ST_ROW_ITEM", "AppVariables", "ID", "Label")\';',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + riIdx + "].TypeAuxData"] = JSON.stringify(riAux);',
    '        }',
    '',
    '        // 2. Configure Labor_Involvement as Enum of BaseType Ref to AppVariables',
    '        var liIdx = tAttrs.findIndex(function(a) { return a.Name === "Labor_Involvement"; });',
    '        if (liIdx >= 0) {',
    '            var li = tAttrs[liIdx];',
    '            var liValidIf = \'=LIST("INV_REGULAR", "INV_OCCASIONAL", "INV_ONLY_RESP", "INV_NOT_RELEVANT")\';',
    '            li.Type = "Enum";',
    '            li.BaseType = "Ref";',
    '            li.ReferencedTableName = "AppVariables";',
    '            li.ReferencedRootTableName = "AppVariables";',
    '            li.Valid_If = liValidIf;',
    '            li.ValidIf = liValidIf;',
    '            li.EnumValues = [];',
    '            li.Description = "";',
    '            li.DisplayName = \'=LOOKUP("Q_ST_LABOR_INV", "AppVariables", "ID", "Label")\';',
    '',
    '            var liAux = {};',
    '            try { liAux = typeof li.TypeAuxData === "string" ? JSON.parse(li.TypeAuxData) : (li.TypeAuxData || {}); } catch(e) {}',
    '            liAux.BaseType = "Ref";',
    '            liAux.ReferencedTableName = "AppVariables";',
    '            liAux.ReferencedRootTableName = "AppVariables";',
    '            liAux.ReferencedKeyColumn = "ID";',
    '            liAux.Valid_If = liValidIf;',
    '            li.TypeAuxData = liAux;',
    '',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].Type"] = "Enum";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].BaseType"] = "Ref";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].ReferencedTableName"] = "AppVariables";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].ReferencedRootTableName"] = "AppVariables";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].Valid_If"] = liValidIf;',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].Description"] = "";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].DisplayName"] = \'=LOOKUP("Q_ST_LABOR_INV", "AppVariables", "ID", "Label")\';',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + liIdx + "].TypeAuxData"] = JSON.stringify(liAux);',
    '        }',
    '',
    '        // 3. Configure Loan_Usage as Enum of BaseType Ref to AppVariables',
    '        var luIdx = tAttrs.findIndex(function(a) { return a.Name === "Loan_Usage"; });',
    '        if (luIdx >= 0) {',
    '            var lu = tAttrs[luIdx];',
    '            var luValidIf = \'=LIST("USE_SEED_CAPITAL", "USE_NEW_MACHINE", "USE_ASSETS_STORE", "USE_EXPAND_SPACE", "USE_RANGE_VARIETY", "USE_SCALE_VOLUME", "USE_VEHICLE", "USE_TRANSPORT", "USE_SMARTPHONE", "USE_OTHER", "USE_NOT_USED")\';',
    '            lu.Type = "Enum";',
    '            lu.BaseType = "Ref";',
    '            lu.ReferencedTableName = "AppVariables";',
    '            lu.ReferencedRootTableName = "AppVariables";',
    '            lu.Valid_If = luValidIf;',
    '            lu.ValidIf = luValidIf;',
    '            lu.EnumValues = [];',
    '            lu.Description = "";',
    '            lu.DisplayName = \'=LOOKUP("Q_ST_LOAN_USE", "AppVariables", "ID", "Label")\';',
    '',
    '            var luAux = {};',
    '            try { luAux = typeof lu.TypeAuxData === "string" ? JSON.parse(lu.TypeAuxData) : (lu.TypeAuxData || {}); } catch(e) {}',
    '            luAux.BaseType = "Ref";',
    '            luAux.ReferencedTableName = "AppVariables";',
    '            luAux.ReferencedRootTableName = "AppVariables";',
    '            luAux.ReferencedKeyColumn = "ID";',
    '            luAux.Valid_If = luValidIf;',
    '            lu.TypeAuxData = luAux;',
    '',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].Type"] = "Enum";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].BaseType"] = "Ref";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].ReferencedTableName"] = "AppVariables";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].ReferencedRootTableName"] = "AppVariables";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].Valid_If"] = luValidIf;',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].Description"] = "";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].DisplayName"] = \'=LOOKUP("Q_ST_LOAN_USE", "AppVariables", "ID", "Label")\';',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + luIdx + "].TypeAuxData"] = JSON.stringify(luAux);',
    '        }',
    '',
    '        // 4. Configure Table_Type Dynamic DisplayName and Description',
    '        var ttIdx = tAttrs.findIndex(function(a) { return a.Name === "Table_Type"; });',
    '        if (ttIdx >= 0) {',
    '            var tt = tAttrs[ttIdx];',
    '            tt.Description = "";',
    '            tt.DisplayName = \'=LOOKUP("Q_ST_TABLE_TYPE", "AppVariables", "ID", "Label")\';',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + ttIdx + "].Description"] = "";',
    '            dict["AppData.DataSchemas[" + tIdx + "].Attributes[" + ttIdx + "].DisplayName"] = \'=LOOKUP("Q_ST_TABLE_TYPE", "AppVariables", "ID", "Label")\';',
    '        }',
    '',
    '        store.dispatch({ type: "SET_EDITOR_OPTIONS", nameValueDict: dict, recordHistory: true });',
    '        store.dispatch({ type: "SHOW_SAVE_BUTTON", value: true });',
    '',
    '        console.log("[OK] Successfully configured Survey_Tables multilingual dropdown options (Row_Item, Labor_Involvement, Loan_Usage, Table_Type)!");',
    '        console.log("[ACTION] Click the top-right blue SAVE button in AppSheet!");',
    '    } catch(err) {',
    '        console.error("[ERROR]", err.message);',
    '    }',
    '})();',
    ''
]

with open('c:/Users/hardi/AppSheets/projects/CmF_SHG_Women_Entrepreneurs/scripts/configure_survey_tables_multilingual_options.js', 'w', encoding='utf-8') as f:
    f.write('\n'.join(js_lines))

print('Wrote configure_survey_tables_multilingual_options.js')
